name: djenv
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.5.2
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - django=4.1
  - django-filter=23.2
  - django-tables2=2.5.3
  - djangorestframework=3.14.0
  - et_xmlfile=1.1.0
  - intel-openmp=2023.1.0
  # - libcxx=14.0.6
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  # - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.25.0
  - numpy-base=1.25.0
  - openpyxl=3.0.10
  - openssl=3.0.9
  - pandas=1.5.3
  - pip=23.1.2
  - python=3.11.3
  - python-dateutil=2.8.2
  - pytz=2023.3
  # - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - sqlparse=0.4.3
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
# prefix: /usr/local/Caskroom/miniconda/base/envs/djenv
