# Generated by Django 4.1 on 2023-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32, verbose_name='品牌')),
                ('model', models.CharField(max_length=64, verbose_name='型号')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存')),
                ('period', models.CharField(max_length=32, verbose_name='周期')),
                ('source', models.CharField(max_length=64, verbose_name='来源')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.IntegerField()),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
