# Generated by Django 4.1 on 2023-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stockapp', '0003_alter_product_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=32, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='product',
            name='period',
            field=models.CharField(blank=True, max_length=32, verbose_name='周期'),
        ),
    ]
