# Generated by Django 4.1 on 2023-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='checksum',
            field=models.CharField(max_length=64, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='name',
            field=models.CharField(max_length=64, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='size',
            field=models.IntegerField(verbose_name='文件大小'),
        ),
    ]
