# Generated by Django 4.1 on 2023-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_product_file_id_alter_productfile_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit_point',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_id',
            field=models.IntegerField(default=-1, verbose_name='文件ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, max_length=64, verbose_name='来源文件'),
        ),
    ]
